//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdesseCaseStudy.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLanguage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdesseCaseStudy.Resources.Languages.AppLanguage", typeof(AppLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idesse App.
        /// </summary>
        internal static string _Shared_AppName {
            get {
                return ResourceManager.GetString("_Shared_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        internal static string _Shared_Cancel {
            get {
                return ResourceManager.GetString("_Shared_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilinmeyen bir hata oluştu!.
        /// </summary>
        internal static string _Shared_Error {
            get {
                return ResourceManager.GetString("_Shared_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string _Shared_LanguageEN {
            get {
                return ResourceManager.GetString("_Shared_LanguageEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        internal static string _Shared_LanguageTR {
            get {
                return ResourceManager.GetString("_Shared_LanguageTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekleyiniz...
        /// </summary>
        internal static string _Shared_Loading {
            get {
                return ResourceManager.GetString("_Shared_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış yapmak istiyor musunuz?.
        /// </summary>
        internal static string _Shared_Logout_Message {
            get {
                return ResourceManager.GetString("_Shared_Logout_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hayır.
        /// </summary>
        internal static string _Shared_No {
            get {
                return ResourceManager.GetString("_Shared_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamam.
        /// </summary>
        internal static string _Shared_OK {
            get {
                return ResourceManager.GetString("_Shared_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idesse.
        /// </summary>
        internal static string _Shared_Title {
            get {
                return ResourceManager.GetString("_Shared_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evet.
        /// </summary>
        internal static string _Shared_Yes {
            get {
                return ResourceManager.GetString("_Shared_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takvim Ekranı.
        /// </summary>
        internal static string CalendarPage_Info {
            get {
                return ResourceManager.GetString("CalendarPage_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLM Ekranı.
        /// </summary>
        internal static string CLMPage_Info {
            get {
                return ResourceManager.GetString("CLMPage_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        internal static string HomePage_Info {
            get {
                return ResourceManager.GetString("HomePage_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        internal static string LoginPage_LoginButton {
            get {
                return ResourceManager.GetString("LoginPage_LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş işlemi başarılı...
        /// </summary>
        internal static string LoginPage_LoginSuccessful {
            get {
                return ResourceManager.GetString("LoginPage_LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı veya Şifresi eksik!.
        /// </summary>
        internal static string LoginPage_LoginValidation {
            get {
                return ResourceManager.GetString("LoginPage_LoginValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre...
        /// </summary>
        internal static string LoginPage_Password_Placeholder {
            get {
                return ResourceManager.GetString("LoginPage_Password_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        internal static string LoginPage_Password_Title {
            get {
                return ResourceManager.GetString("LoginPage_Password_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        internal static string LoginPage_Title {
            get {
                return ResourceManager.GetString("LoginPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı...
        /// </summary>
        internal static string LoginPage_Username_Placeholder {
            get {
                return ResourceManager.GetString("LoginPage_Username_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        internal static string LoginPage_Username_Title {
            get {
                return ResourceManager.GetString("LoginPage_Username_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoşgeldin, {0}.
        /// </summary>
        internal static string LoginPage_Welcome {
            get {
                return ResourceManager.GetString("LoginPage_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merhaba.
        /// </summary>
        internal static string Menu_Hello {
            get {
                return ResourceManager.GetString("Menu_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takvim.
        /// </summary>
        internal static string Menu_Item_Calendar {
            get {
                return ResourceManager.GetString("Menu_Item_Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLM.
        /// </summary>
        internal static string Menu_Item_CLM {
            get {
                return ResourceManager.GetString("Menu_Item_CLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        internal static string Menu_Item_Home {
            get {
                return ResourceManager.GetString("Menu_Item_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yap.
        /// </summary>
        internal static string Menu_Item_LogOut {
            get {
                return ResourceManager.GetString("Menu_Item_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş.
        /// </summary>
        internal static string Menu_Item_Orders {
            get {
                return ResourceManager.GetString("Menu_Item_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kişiler.
        /// </summary>
        internal static string Menu_Item_Persons {
            get {
                return ResourceManager.GetString("Menu_Item_Persons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        internal static string Menu_Item_Settings {
            get {
                return ResourceManager.GetString("Menu_Item_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üniteler.
        /// </summary>
        internal static string Menu_Item_Units {
            get {
                return ResourceManager.GetString("Menu_Item_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menüde ara...
        /// </summary>
        internal static string Menu_Search {
            get {
                return ResourceManager.GetString("Menu_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Ekranı.
        /// </summary>
        internal static string OrdersPage_Info {
            get {
                return ResourceManager.GetString("OrdersPage_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama için en az 4 karakter girin...
        /// </summary>
        internal static string PersonPage_SearchText {
            get {
                return ResourceManager.GetString("PersonPage_SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar Ekranı.
        /// </summary>
        internal static string SettingsPage_Info {
            get {
                return ResourceManager.GetString("SettingsPage_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Seçin.
        /// </summary>
        internal static string SettingsPage_LanguageChoose {
            get {
                return ResourceManager.GetString("SettingsPage_LanguageChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Seçenekleri.
        /// </summary>
        internal static string SettingsPage_LanguageTitle {
            get {
                return ResourceManager.GetString("SettingsPage_LanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        internal static string SettingsPage_Save {
            get {
                return ResourceManager.GetString("SettingsPage_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçenekler kaydedildi..
        /// </summary>
        internal static string SettingsPage_SaveMessage {
            get {
                return ResourceManager.GetString("SettingsPage_SaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üniteler Ekranı.
        /// </summary>
        internal static string UnitPage_Info {
            get {
                return ResourceManager.GetString("UnitPage_Info", resourceCulture);
            }
        }
    }
}
